#pragma once

#include "BackupDefault.h"

#include <string>
#include <map>

typedef struct s_SaveInfo {
    BackupType Type;
    GPIODeviceType GPIO;
    bool Mirrored;
    const char* Name;
} s_SaveInfo;

// Adapted from NanoBoy Advance's game_db.cpp:
// https://github.com/fleroviux/NanoboyAdvance/blob/master/source/emulator/cartridge/game_db.cpp
// Fleroviux in term adapted it from VisualBoyAdvance-M's vba-over.ini:
// https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/vba-over.ini
// The original vba-over.ini has no information on EEPROM size.
// I set all Classic NES/Famicon Mini titles to EEPROM_4, since they appear to be
// the exception, most games probably use the larger size.
const static std::map<std::string, s_SaveInfo> GameDB {
        { "ALFP", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Dragon Ball Z - The Legacy of Goku II (Europe)(En,Fr,De,Es,It)" } },
        { "ALGP", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Dragon Ball Z - The Legacy of Goku (Europe)(En,Fr,De,Es,It)" } },
        { "AROP", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Rocky (Europe)(En,Fr,De,Es,It)" } },
        { "AR8e", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Rocky (USA)(En,Fr,De,Es,It)" } },
        { "AXVE", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Ruby Version (USA, Europe)" } },
        { "AXPE", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Sapphire Version (USA, Europe)" } },
        { "AX4P", { BackupType::FLASH_128, GPIODeviceType::None, false, "Super Mario Advance 4 - Super Mario Bros. 3 (Europe)(En,Fr,De,Es,It)" } },
        { "A2YE", { BackupType::SRAM,/*X*/ GPIODeviceType::None, false, "Top Gun - Combat Zones (USA)(En,Fr,De,Es,It)" } },
        { "BDBP", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Dragon Ball Z - Taiketsu (Europe)(En,Fr,De,Es,It)" } },
        { "BM5P", { BackupType::FLASH_64,  GPIODeviceType::None, false, "Mario vs. Donkey Kong (Europe)" } },
        { "BPEE", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Emerald Version (USA, Europe)" } },
        { "BY6P", { BackupType::SRAM,      GPIODeviceType::None, false, "Yu-Gi-Oh! - Ultimate Masters - World Championship Tournament 2006 (Europe)(En,Jp,Fr,De,Es,It)" } },
        { "B24E", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon Mystery Dungeon - Red Rescue Team (USA, Australia)" } },
        { "FADE", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Castlevania (USA, Europe)" } },
        { "FBME", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Bomberman (USA, Europe)" } },
        { "FDKE", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Donkey Kong (USA, Europe)" } },
        { "FDME", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Dr. Mario (USA, Europe)" } },
        { "FEBE", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Excitebike (USA, Europe)" } },
        { "FICE", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Ice Climber (USA, Europe)" } },
        { "FLBE", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Zelda II - The Adventure of Link (USA, Europe)" } },
        { "FMRE", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Metroid (USA, Europe)" } },
        { "FP7E", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Pac-Man (USA, Europe)" } },
        { "FSME", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Super Mario Bros. (USA, Europe)" } },
        { "FXVE", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Classic NES Series - Xevious (USA, Europe)" } },
        { "FZLE", { BackupType::EEPROM_64, GPIODeviceType::None, true,  "Classic NES Series - Legend of Zelda (USA, Europe)" } },
        { "KYGP", { BackupType::EEPROM_64/*_SENSOR*/, GPIODeviceType::None, false, "Yoshi's Universal Gravitation (Europe)(En,Fr,De,Es,It)" } },
        { "U3IP", { BackupType::Detect,    GPIODeviceType::RTC,  false, "Boktai - The Sun Is in Your Hand (Europe)(En,Fr,De,Es,It)" } },
        { "U32P", { BackupType::Detect,    GPIODeviceType::RTC,  false, "Boktai 2 - Solar Boy Django (Europe)(En,Fr,De,Es,It)" } },
        { "AGFE", { BackupType::FLASH_64,  GPIODeviceType::RTC,  false, "Golden Sun - The Lost Age (USA)" } },
        { "AGSE", { BackupType::FLASH_64,  GPIODeviceType::RTC,  false, "Golden Sun (USA)" } },
        { "ALFE", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Dragon Ball Z - The Legacy of Goku II (USA)" } },
        { "ALGE", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Dragon Ball Z - The Legacy of Goku (USA)" } },
        { "AX4E", { BackupType::FLASH_128, GPIODeviceType::None, false, "Super Mario Advance 4 - Super Mario Bros 3 - Super Mario Advance 4 v1.1 (USA)" } },
        { "BDBE", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Dragon Ball Z - Taiketsu (USA)" } },
        { "BG3E", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Dragon Ball Z - Buu's Fury (USA)" } },
        { "BLFE", { BackupType::EEPROM_64, GPIODeviceType::None, false, "2 Games in 1 - Dragon Ball Z - The Legacy of Goku I & II (USA)" } },
        { "BPRE", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Fire Red Version (USA, Europe)" } },
        { "BPGE", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Leaf Green Version (USA, Europe)" } },
        { "BT4E", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Dragon Ball GT - Transformation (USA)" } },
        { "BUFE", { BackupType::EEPROM_64, GPIODeviceType::None, false, "2 Games in 1 - Dragon Ball Z - Buu's Fury + Dragon Ball GT - Transformation (USA)" } },
        { "BYGE", { BackupType::SRAM,      GPIODeviceType::None, false, "Yu-Gi-Oh! GX - Duel Academy (USA)" } },
        { "KYGE", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Yoshi - Topsy-Turvy (USA)" } },
        { "PSAE", { BackupType::FLASH_128, GPIODeviceType::None, false, "e-Reader (USA)" } },
        { "U3IE", { BackupType::Detect,    GPIODeviceType::RTC,  false, "Boktai - The Sun Is in Your Hand (USA)" } },
        { "U32E", { BackupType::Detect,    GPIODeviceType::RTC,  false, "Boktai 2 - Solar Boy Django (USA)" } },
        { "ALFJ", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Dragon Ball Z - The Legacy of Goku II International (Japan)" } },
        { "AXPJ", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pocket Monsters - Sapphire (Japan)" } },
        { "AXVJ", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pocket Monsters - Ruby (Japan)" } },
        { "AX4J", { BackupType::FLASH_128, GPIODeviceType::None, false, "Super Mario Advance 4 (Japan)" } },
        { "BFTJ", { BackupType::FLASH_128, GPIODeviceType::None, false, "F-Zero - Climax (Japan)" } },
        { "BGWJ", { BackupType::FLASH_128, GPIODeviceType::None, false, "Game Boy Wars Advance 1+2 (Japan)" } },
        { "BKAJ", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Sennen Kazoku (Japan)" } },
        { "BPEJ", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pocket Monsters - Emerald (Japan)" } },
        { "BPGJ", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pocket Monsters - Leaf Green (Japan)" } },
        { "BPRJ", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pocket Monsters - Fire Red (Japan)" } },
        { "BDKJ", { BackupType::EEPROM_64, GPIODeviceType::None, false, "Digi Communication 2 - Datou! Black Gemagema Dan (Japan)" } },
        { "BR4J", { BackupType::Detect,    GPIODeviceType::RTC,  false, "Rockman EXE 4.5 - Real Operation (Japan)" } },
        { "FMBJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 01 - Super Mario Bros. (Japan)" } },
        { "FCLJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 12 - Clu Clu Land (Japan)" } },
        { "FBFJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 13 - Balloon Fight (Japan)" } },
        { "FWCJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 14 - Wrecking Crew (Japan)" } },
        { "FDMJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 15 - Dr. Mario (Japan)" } },
        { "FDDJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 16 - Dig Dug (Japan)" } },
        { "FTBJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 17 - Takahashi Meijin no Boukenjima (Japan)" } },
        { "FMKJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 18 - Makaimura (Japan)" } },
        { "FTWJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 19 - Twin Bee (Japan)" } },
        { "FGGJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 20 - Ganbare Goemon! Karakuri Douchuu (Japan)" } },
        { "FM2J", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 21 - Super Mario Bros. 2 (Japan)" } },
        { "FNMJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 22 - Nazo no Murasame Jou (Japan)" } },
        { "FMRJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 23 - Metroid (Japan)" } },
        { "FPTJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 24 - Hikari Shinwa - Palthena no Kagami (Japan)" } },
        { "FLBJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 25 - The Legend of Zelda 2 - Link no Bouken (Japan)" } },
        { "FFMJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 26 - Famicom Mukashi Banashi - Shin Onigashima - Zen Kou Hen (Japan)" } },
        { "FTKJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 27 - Famicom Tantei Club - Kieta Koukeisha - Zen Kou Hen (Japan)" } },
        { "FTUJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 28 - Famicom Tantei Club Part II - Ushiro ni Tatsu Shoujo - Zen Kou Hen (Japan)" } },
        { "FADJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 29 - Akumajou Dracula (Japan)" } },
        { "FSDJ", { BackupType::EEPROM_4,  GPIODeviceType::None, true,  "Famicom Mini Vol. 30 - SD Gundam World - Gachapon Senshi Scramble Wars (Japan)" } },
        { "KHPJ", { BackupType::EEPROM_64/*_SENSOR*/, GPIODeviceType::None, false, "Koro Koro Puzzle - Happy Panechu! (Japan)" } },
        { "KYGJ", { BackupType::EEPROM_64/*_SENSOR*/, GPIODeviceType::None, false, "Yoshi no Banyuuinryoku (Japan)" } },
        { "PSAJ", { BackupType::FLASH_128, GPIODeviceType::None, false, "Card e-Reader+ (Japan)" } },
        { "U3IJ", { BackupType::Detect,    GPIODeviceType::RTC,  false, "Bokura no Taiyou - Taiyou Action RPG (Japan)" } },
        { "U32J", { BackupType::Detect,    GPIODeviceType::RTC,  false, "Zoku Bokura no Taiyou - Taiyou Shounen Django (Japan)" } },
        { "U33J", { BackupType::Detect,    GPIODeviceType::RTC,  false, "Shin Bokura no Taiyou - Gyakushuu no Sabata (Japan)" } },
        { "AXPF", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Version Saphir (France)" } },
        { "AXVF", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Version Rubis (France)" } },
        { "BPEF", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Version Emeraude (France)" } },
        { "BPGF", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Version Vert Feuille (France)" } },
        { "BPRF", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Version Rouge Feu (France)" } },
        { "AXPI", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Versione Zaffiro (Italy)" } },
        { "AXVI", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Versione Rubino (Italy)" } },
        { "BPEI", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Versione Smeraldo (Italy)" } },
        { "BPGI", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Versione Verde Foglia (Italy)" } },
        { "BPRI", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Versione Rosso Fuoco (Italy)" } },
        { "AXPD", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Saphir-Edition (Germany)" } },
        { "AXVD", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Rubin-Edition (Germany)" } },
        { "BPED", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Smaragd-Edition (Germany)" } },
        { "BPGD", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Blattgruene Edition (Germany)" } },
        { "BPRD", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Feuerrote Edition (Germany)" } },
        { "AXPS", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Edicion Zafiro (Spain)" } },
        { "AXVS", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Edicion Rubi (Spain)" } },
        { "BPES", { BackupType::FLASH_128, GPIODeviceType::RTC,  false, "Pokemon - Edicion Esmeralda (Spain)" } },
        { "BPGS", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Edicion Verde Hoja (Spain)" } },
        { "BPRS", { BackupType::FLASH_128, GPIODeviceType::None, false, "Pokemon - Edicion Rojo Fuego (Spain)" } },
        { "A9DP", { BackupType::EEPROM_4,  GPIODeviceType::None, false, "DOOM II" } },
        { "AAOJ", { BackupType::EEPROM_4,  GPIODeviceType::None, false, "Acrobat Kid (Japan)" } },
        { "BGDP", { BackupType::EEPROM_4,  GPIODeviceType::None, false, "Baldur's Gate - Dark Alliance (Europe)" } },
        { "BGDE", { BackupType::EEPROM_4,  GPIODeviceType::None, false, "Baldur's Gate - Dark Alliance (USA)" } },
        { "BJBE", { BackupType::EEPROM_4,  GPIODeviceType::None, false, "007 - Everything or Nothing (USA, Europe) (En,Fr,De)" } },
        { "BJBJ", { BackupType::EEPROM_4,  GPIODeviceType::None, false, "007 - Everything or Nothing (Japan)" } },
        { "ALUP", { BackupType::EEPROM_4,  GPIODeviceType::None, false, "0937 - Super Monkey Ball Jr. (Europe)" } },
        { "ALUE", { BackupType::EEPROM_4,  GPIODeviceType::None, false, "0763 - Super Monkey Ball Jr. (USA)" } },
};
